# Generated by Django 2.1.4 on 2018-12-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciept',
            name='user_email',
        ),
        migrations.AlterField(
            model_name='reciept',
            name='client_name',
            field=models.ForeignKey(on_delete=False, to='client.Client'),
        ),
    ]
