# Generated by Django 2.1.4 on 2019-01-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20190122_1035'),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.IntegerField()),
                ('policy_number', models.IntegerField()),
                ('paying_term', models.IntegerField()),
                ('maturity_term', models.IntegerField()),
                ('premium', models.IntegerField()),
                ('mode', models.CharField(max_length=20)),
                ('DOC', models.DateTimeField()),
                ('client_name', models.ForeignKey(on_delete=True, to='client.Client')),
            ],
        ),
    ]
