# Generated by Django 2.1.4 on 2019-01-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_client_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_policy',
            name='uname',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
