# Generated by Django 2.1.4 on 2019-01-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_client_policy_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_policy',
            name='uname',
            field=models.EmailField(max_length=254),
        ),
    ]
