# Generated by Django 2.1.4 on 2019-01-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_auto_20190122_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_policy',
            name='client_name',
        ),
    ]
